version: "3.9"
services:
  gisdb:
    build: 
      context: . 
      dockerfile: db/Dockerfile
    # image: postgis/postgis:11-2.5-alpine

    ports:
      - 5433:5432
    container_name: gisdb
    
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}

    env_file:
      - .env

    # volumes:
    #   - pgdata:/opt/drupal/web/modules
    #   # libraries 
      # - ./exports:/testdir:cached
      # - ./config:/opt/drupal/web/
# volumes:
#   pgdata:
